// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateConfig(arg1:main.ConfigData):Promise<string>;

export function DeleteConfig(arg1:string):Promise<string>;

export function ExportConfig(arg1:string):Promise<string>;

export function GetConfigs():Promise<Array<main.ConfigInfo>>;

export function GetLogs(arg1:number):Promise<Array<string>>;

export function GetProviderDefaults(arg1:string):Promise<Record<string, string>>;

export function GetStatus():Promise<main.StatusInfo>;

export function GetSupportedProviders():Promise<Array<main.ProviderInfo>>;

export function GetSystemInfo():Promise<main.SystemInfo>;

export function ImportConfig(arg1:string,arg2:string):Promise<string>;

export function ImportConfigFromFile(arg1:string,arg2:string):Promise<string>;

export function ImportConfigFromJSON(arg1:string,arg2:string):Promise<string>;

export function InstallCACert():Promise<string>;

export function LoadConfigFile(arg1:string):Promise<string>;

export function OpenDirectoryDialog():Promise<string>;

export function OpenFileDialog():Promise<string>;

export function StartProxy(arg1:string,arg2:number):Promise<string>;

export function StopProxy():Promise<string>;

export function TestConnection(arg1:string):Promise<main.TestResult>;

export function UninstallCACert():Promise<string>;

export function UpdateConfig(arg1:main.ConfigData):Promise<string>;
