// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateConfig(arg1) {
  return window['go']['main']['App']['CreateConfig'](arg1);
}

export function DeleteConfig(arg1) {
  return window['go']['main']['App']['DeleteConfig'](arg1);
}

export function ExportConfig(arg1) {
  return window['go']['main']['App']['ExportConfig'](arg1);
}

export function GetConfigs() {
  return window['go']['main']['App']['GetConfigs']();
}

export function GetLogs(arg1) {
  return window['go']['main']['App']['GetLogs'](arg1);
}

export function GetProviderDefaults(arg1) {
  return window['go']['main']['App']['GetProviderDefaults'](arg1);
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetSupportedProviders() {
  return window['go']['main']['App']['GetSupportedProviders']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function ImportConfig(arg1, arg2) {
  return window['go']['main']['App']['ImportConfig'](arg1, arg2);
}

export function ImportConfigFromFile(arg1, arg2) {
  return window['go']['main']['App']['ImportConfigFromFile'](arg1, arg2);
}

export function ImportConfigFromJSON(arg1, arg2) {
  return window['go']['main']['App']['ImportConfigFromJSON'](arg1, arg2);
}

export function InstallCACert() {
  return window['go']['main']['App']['InstallCACert']();
}

export function LoadConfigFile(arg1) {
  return window['go']['main']['App']['LoadConfigFile'](arg1);
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function StartProxy(arg1, arg2) {
  return window['go']['main']['App']['StartProxy'](arg1, arg2);
}

export function StopProxy() {
  return window['go']['main']['App']['StopProxy']();
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}

export function UninstallCACert() {
  return window['go']['main']['App']['UninstallCACert']();
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}
